Remove real estate related code from executive summary
RMI-PACTA/pacta.executive.summary pull request #307
Opened 2024-05-07 15:26 UTC by MonikaFu

2024-05-07 17:06 UTC, jdhoffa approved these changes
lgtm

2024-05-07 17:08 UTC, jdhoffa requested changes
Make sure to re-document the code! Then LGTM

2024-05-07 21:13 UTC, cjyetman approved these changes

2024-05-08 09:33 UTC, merged

2024-05-08 13:41 UTC, jdhoffa commented
@cjyetman @MonikaFu just noting that this was merged with 5/8 checks failing. 

Please look into that ASAP, it still seems like a documentation issue.