Add french translations
RMI-PACTA/pacta.executive.summary pull request #360
Opened 2024-09-11 13:08 UTC by Antoine-Lalechere

@MonikaFu 

PR ready to review :)

2024-09-11 14:45 UTC, MonikaFu requested changes

2024-09-11 14:45 UTC, MonikaFu commented on inst/extdata/PA2024CH_fr_exec_summary/scorecard.Rmd
> +Companies are increasingly making voluntary commitments to transition to net-zero and set interim targets. The effectiveness of such commitments depends on whether interim targets are credible, scien
This part should be translated to French.

2024-09-11 14:45 UTC, MonikaFu commented
@Antoine-Lalechere see my comment.

2024-09-11 14:55 UTC, MonikaFu commented on inst/extdata/PA2024CH_fr_exec_summary/scorecard.Rmd
>  \subsection{Credible Climate Stewardship}
This should be translated as well

2024-09-11 14:58 UTC, MonikaFu requested changes

2024-09-11 15:24 UTC, Antoine-Lalechere commented on inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
>  \end{itemize}
changes done @MonikaFu

2024-09-11 15:48 UTC, MonikaFu requested changes
It seems to me from a brief look that a lot of parts between `UPDATED` tags from [English version of the ES](https://github.com/RMI-PACTA/pacta.executive.summary/blob/main/inst/extdata/PA2024CH_en_exec_summary/template.Rmd) in `template.Rmd` is missing. Can you please check again if you covered all of them?

2024-09-11 15:48 UTC, MonikaFu commented on inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
> +La Suisse et son marché financier se sont engagés à passer à zéro émission nette de gaz à effet de serre d'ici à 2050 afin d'atteindre les objectifs de l'accord de Paris sur le climat visant à limite
Is this translation based on the new English version? It seems to me that it uses old number of participating institutions (it should be 122) and it misses som `textbf{}` marks from the current version. The intro changed quite a lot this time so it should all be translated again I believe. See the English version between tags `UPDATED 1 and UPDATED 1 END`.

2024-09-12 10:00 UTC, MonikaFu requested changes

2024-09-12 10:00 UTC, MonikaFu commented on inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
> +\textbf{La Suisse et son marché financier se sont engagés à atteindre des émissions nettes de carbone nulles d'ici 2050} afin de remplir ses engagements en vertu de la loi suisse sur le climat et l'i
change `\ref` to '\href`

2024-09-12 10:00 UTC, MonikaFu commented on inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
Please remove, 'TO BE REVIEWED' line.

2024-09-12 10:00 UTC, MonikaFu commented on inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
Line 390 - there are still references to GECO 2021

2024-09-12 10:00 UTC, MonikaFu commented on inst/extdata/PA2024CH_fr_exec_summary/template.Rmd
See `UPDATED 4:` - the footnote seems not to be updated correctly as it mentiond GECO 2021 as well in the English version and I don't see it in the French.

2024-09-12 10:00 UTC, MonikaFu commented
@Antoine-Lalechere please see my comments

2024-09-12 12:37 UTC, MonikaFu approved these changes
LGTM. However I am not able to check the translation language-wise. The summary does compile and I don't see obvious references to the previous COP.

2024-09-12 12:43 UTC, merged